INSERT INTO GOOD_LINE_CLI_SCHEME.USERS (USER_NAME, USER_LOGIN, USER_PASS_HASH, USER_SALT) VALUES ('JonDoe', 'jdoe', '69fa729c5846be455faee3eba3c93e4d', '+NSw]7');
INSERT INTO GOOD_LINE_CLI_SCHEME.USERS(USER_NAME, USER_LOGIN, USER_PASS_HASH, USER_SALT) VALUES ('JaneRow', 'jrow', 'c0efab8ae7ca062877fee6b9bf00a7d7', '7xpK2L$');

INSERT INTO GOOD_LINE_CLI_SCHEME.USER_RESOURCES (USER_ID, USER_RESOURCE_PATH, USER_RESOURCE_ROLE) VALUES (1, 'a', 'READ');
INSERT INTO GOOD_LINE_CLI_SCHEME.USER_RESOURCES (USER_ID, USER_RESOURCE_PATH, USER_RESOURCE_ROLE) VALUES (1, 'a.b', 'WRITE');
INSERT INTO GOOD_LINE_CLI_SCHEME.USER_RESOURCES (USER_ID, USER_RESOURCE_PATH, USER_RESOURCE_ROLE) VALUES (2, 'a.b.c', 'EXECUTE');
INSERT INTO GOOD_LINE_CLI_SCHEME.USER_RESOURCES (USER_ID, USER_RESOURCE_PATH, USER_RESOURCE_ROLE) VALUES (1, 'a.bc', 'EXECUTE');